name: Require Approval

on:
  pull_request:
    types: [opened, synchronize, reopened]
  pull_request_review:
    types: [submitted]

jobs:
  require-approval:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Check approvals
      id: approval-check
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        approvals=$(gh pr view ${{ github.event.pull_request.number }} --json reviews --jq '.reviews | map(select(.state == "APPROVED")) | length')
        echo "approvals=$approvals" >> $GITHUB_OUTPUT

    - name: Fail if no approvals
      if: steps.approval-check.outputs.approvals == '0'
      run: |
        echo ":closed_lock_with_key: This PR must have at least one approval to be merged."
        exit 1
